require('@babel/runtime/regenerator')
require('react-hot-loader/patch')
require('@babel/register')
require('webpack-hot-middleware/client?reload=true')
require('./main.css')
require('./index.html')
require('./app')
